name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use v2 of actions/checkout

    - name: Run custom Bash script
      run: bash test.sh  # Replace with the name of your Bash script


    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
