name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use v2 for checkout action

    - name: Set up build environment
      run: sudo apt-get install -y build-essential cmake

    - name: Make build script executable
      run: chmod +x ./build_project.sh

    - name: Run build script
      run: ./build_project.sh
